@include('sections.home.hero', ['hero' => $hero ?? null])
@include('sections.home.footnote-cards', ['footnoteCards' => $footnoteCards ?? ['items' => []]])
@include('sections.home.membership')
@include('sections.home.stats')
@include('partials.decorators.decorator-1')
@include('sections.home.cpd-intro')
@include('sections.home.tabbed-content')
@include('sections.home.testimonials')
@include('partials.decorators.decorator-2')
@include('sections.home.about-intro')
@include('sections.home.diversity')
@include('sections.home.cta-section')
@include('partials.decorators.decorator-3')
@include('sections.home.faq')
@include('sections.home.newsletter')
