@include('sections.home.hero', ['hero' => $hero ?? null])
@include('sections.home.footnote-cards', ['footnoteCards' => $footnoteCards ?? ['items' => []]])
@include('sections.home.membership', ['membership' => $membership ?? null])
@include('sections.home.stats', ['stats' => $stats ?? ['items' => []]])
@include('partials.decorators.decorator-1')
@include('sections.home.cpd-intro', ['cpdIntro' => $cpdIntro ?? null])
@include('sections.home.tabbed-content', ['tabbedContent' => $tabbedContent ?? ['tabs' => []]])
@include('sections.home.testimonials', ['testimonials' => $testimonials ?? ['items' => []]])
@include('partials.decorators.decorator-2')
@include('sections.home.about-intro')
@include('sections.home.diversity')
@include('sections.home.cta-section')
@include('partials.decorators.decorator-3')
@include('sections.home.faq')
@include('sections.home.newsletter')
