<?php

namespace App\Support;

final class MemberFieldMap
{
    /** @var array<string, string> Excel 中文列名 => 数据库字段 */
    public const EXCEL_TO_DB = [
        '持证会员编号' => 'member_number',
        '称谓' => 'salutation',
        '姓名' => 'full_name',
        '名' => 'first_name',
        '姓' => 'last_name',
        '性别' => 'gender',
        '生日' => 'birth_date',
        '手机号' => 'mobile_phone',
        '邮箱' => 'email',
        '证件类型' => 'id_type',
        '证件号码' => 'id_number',
        '持证会籍资格状态' => 'membership_status',
        '会员级别' => 'member_level',
        '持证会员级别简称' => 'member_level_short',
        '会员标签' => 'member_tags',
        '加入日期' => 'joined_at',
        '会员级别有效期' => 'level_valid_until',
        '会龄' => 'membership_years',
        '当前级别会龄' => 'current_level_years',
        '职务头衔(中)' => 'job_title_zh',
        '职务头衔(英)' => 'job_title_en',
        '公司名称(中)' => 'company_name_zh',
        '公司名称(英)' => 'company_name_en',
        '工作电话' => 'work_phone',
        '家庭电话' => 'home_phone',
        '传真' => 'fax',
        '微信账号' => 'wechat',
        '其他社交媒体' => 'other_social_platform',
        '其他社交媒体账号' => 'other_social_account',
        '备用电子邮箱' => 'alternate_email',
        '一级合作伙伴' => 'partner_level_1',
        '二级合作伙伴' => 'partner_level_2',
        '持证会员所属区' => 'region',
        '是否享受评审优惠政策' => 'review_discount',
        '是否特批' => 'special_approval',
        '联系人（助理)' => 'assistant_contact',
        '联系人电话' => 'assistant_phone',
        '推荐人手机号' => 'referrer_mobile',
        '推荐人' => 'referrer_name',
        '推荐人持证会员编号' => 'referrer_member_number',
        '证书姓名' => 'certificate_name',
        '证书已打印' => 'certificate_printed',
        '证书发放日期' => 'certificate_issued_at',
        '考试情况' => 'exam_status',
        'IFRS' => 'ifrs',
        'Ethics' => 'ethics',
        'BDA' => 'bda',
        '继续教育学分' => 'cpd_credits',
        '持证会籍资格恢复日期' => 'membership_restored_at',
        '持证会籍资格升级日期' => 'membership_upgraded_at',
        '持证会籍资格转移日期' => 'membership_transferred_at',
        '请假申请理由' => 'leave_reason',
        '请假申请到期日期' => 'leave_expires_at',
        '持证资格终止or请假申请理由' => 'termination_or_leave_reason',
        '持证资格终止or请假申请日期' => 'termination_or_leave_at',
        '持证会籍资格申请日期' => 'membership_application_at',
        '持证会籍资格申请类型' => 'membership_application_type',
        '持证会籍资格申请状态' => 'membership_application_status',
        '持证会籍资格申请申请状态日期' => 'membership_application_status_at',
        '持证会籍资格申请评估日期' => 'membership_application_review_at',
        '持证会籍资格申请评估人' => 'membership_application_reviewer',
        '备注' => 'notes',
    ];

    /** @var array<string, string> */
    public const DB_LABELS = [
        'member_number' => '持证会员编号',
        'salutation' => '称谓',
        'full_name' => '姓名',
        'first_name' => '名',
        'last_name' => '姓',
        'gender' => '性别',
        'birth_date' => '生日',
        'mobile_phone' => '手机号',
        'email' => '邮箱',
        'id_type' => '证件类型',
        'id_number' => '证件号码',
        'membership_status' => '持证会籍资格状态',
        'member_level' => '会员级别',
        'member_level_short' => '持证会员级别简称',
        'member_tags' => '会员标签',
        'joined_at' => '加入日期',
        'level_valid_until' => '会员级别有效期',
        'membership_years' => '会龄',
        'current_level_years' => '当前级别会龄',
        'job_title_zh' => '职务头衔(中)',
        'job_title_en' => '职务头衔(英)',
        'company_name_zh' => '公司名称(中)',
        'company_name_en' => '公司名称(英)',
        'work_phone' => '工作电话',
        'home_phone' => '家庭电话',
        'fax' => '传真',
        'wechat' => '微信账号',
        'other_social_platform' => '其他社交媒体',
        'other_social_account' => '其他社交媒体账号',
        'alternate_email' => '备用电子邮箱',
        'partner_level_1' => '一级合作伙伴',
        'partner_level_2' => '二级合作伙伴',
        'region' => '持证会员所属区',
        'review_discount' => '是否享受评审优惠政策',
        'special_approval' => '是否特批',
        'assistant_contact' => '联系人（助理)',
        'assistant_phone' => '联系人电话',
        'referrer_mobile' => '推荐人手机号',
        'referrer_name' => '推荐人',
        'referrer_member_number' => '推荐人持证会员编号',
        'certificate_name' => '证书姓名',
        'certificate_printed' => '证书已打印',
        'certificate_issued_at' => '证书发放日期',
        'exam_status' => '考试情况',
        'ifrs' => 'IFRS',
        'ethics' => 'Ethics',
        'bda' => 'BDA',
        'cpd_credits' => '继续教育学分',
        'membership_restored_at' => '持证会籍资格恢复日期',
        'membership_upgraded_at' => '持证会籍资格升级日期',
        'membership_transferred_at' => '持证会籍资格转移日期',
        'leave_reason' => '请假申请理由',
        'leave_expires_at' => '请假申请到期日期',
        'termination_or_leave_reason' => '持证资格终止or请假申请理由',
        'termination_or_leave_at' => '持证资格终止or请假申请日期',
        'membership_application_at' => '持证会籍资格申请日期',
        'membership_application_type' => '持证会籍资格申请类型',
        'membership_application_status' => '持证会籍资格申请状态',
        'membership_application_status_at' => '持证会籍资格申请申请状态日期',
        'membership_application_review_at' => '持证会籍资格申请评估日期',
        'membership_application_reviewer' => '持证会籍资格申请评估人',
        'notes' => '备注',
    ];

    public static function dateFields(): array
    {
        return [
            'birth_date',
            'joined_at',
            'level_valid_until',
            'certificate_issued_at',
            'membership_restored_at',
            'membership_upgraded_at',
            'membership_transferred_at',
            'leave_expires_at',
            'termination_or_leave_at',
            'membership_application_at',
            'membership_application_status_at',
            'membership_application_review_at',
        ];
    }

    public static function profileFields(): array
    {
        return [
            'first_name',
            'full_name',
            'last_name',
            'salutation',
            'job_title_zh',
            'job_title_en',
            'company_name_zh',
            'company_name_en',
            'birth_date',
            'gender',
            'mobile_phone',
            'home_phone',
            'work_phone',
            'email',
            'alternate_email',
            'id_type',
            'id_number',
            'wechat',
            'other_social_platform',
            'other_social_account',
            'region',
            'fax',
            'assistant_contact',
            'assistant_phone',
        ];
    }

    public static function membershipHeaderFields(): array
    {
        return [
            'member_number',
            'member_level',
            'member_level_short',
            'joined_at',
            'level_valid_until',
            'membership_status',
            'member_tags',
            'membership_years',
            'current_level_years',
        ];
    }
}
